version: 0.2

env:
  variables:
    TF_DISTRIBUTION: "oss"
    
phases:
  install:
    runtime-versions:
      python: 3.9
    commands:
      - pip install -r requirements.txt
  
  pre_build:
    commands:
      - echo "Starting pre-build phase"
      - cd terraform
  
  build:
    commands:
      - echo "Starting build phase"
      - terraform init
      - terraform plan
      - terraform apply -auto-approve
  
  post_build:
    commands:
      - echo "Build completed"

artifacts:
  files:
    - '**/*'
  base-directory: terraform 